packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@orpc/server": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  better-auth: ^1.4.5
  dotenv: ^17.2.2
  zod: ^4.1.13
  "@orpc/tanstack-query": ^1.12.2
  "@orpc/client": ^1.12.2
  "@tanstack/react-query": ^5.90.12
  "@better-auth/expo": ^1.4.5
